name: "Nix"
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: bernbot
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Tests
      run: nix build .#bernbot-debug
