name: "Nix Run"
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210415_76980a1/install
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: bernbot
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run
      run: DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" nix run .#bernbot-debug-discord -L --show-trace
